### ISSUE TITLE
Account menu - end of the page is cut

### ISSUE THREAD

**Issue by Yzia** [mandelmonkey/bookoforbs#1]
Chrome Version 62.0.3202.94 (Build officiel) (64 bits)

Hi,

As you can see into the screenshot, the page is cut (bitcrystals logo + data). 

![sans titre](https://user-images.githubusercontent.com/34238756/33671264-6e2a8f9e-daa7-11e7-936d-4f1eae58bf04.png)

**Comment by mandelmonkey** [comment]
should be ok now if not please reopen
