### ISSUE TITLE
Market display - Scrolling bar

### ISSUE THREAD

**Issue by Yzia** [mandelmonkey/bookoforbs#10]
Firefox 57.0.2 64bits

From a computer, scrolling the market is really not friendly-use. 
Add a button to load more should be better than the scrolling bar.

![image](https://user-images.githubusercontent.com/34238756/34517217-6f6cdb30-f07a-11e7-9f88-490445e59ccb.png)

**Comment by mandelmonkey** [comment]
Hi
I updated to add a view all button to see all the cards, the original idea was to only show a few cards on the market page, like new cards but let users view all cards via the new button.

But if you think its not a good idea I can raise with shaban
