### ISSUE TITLE
History page - weird blue square 

### ISSUE THREAD

**Issue by Yzia** [mandelmonkey/bookoforbs#12]
Mobile (Samsung S5 SM-G901F / Android 6.0.1 / chrome 63.0.3239.111)

History page, when you click on the buttons a blue transparent square appears
- "Send/Receive" and "Orders"
- "All" "Bought" "Sold" and "Open" when you select an order into the previous menu

![image](https://user-images.githubusercontent.com/34238756/34517453-6641afc6-f07b-11e7-8f26-67112d12a638.png)

**Comment by mandelmonkey** [comment]
should be resolved, I tested on android, may need to reload the webpage/close browser for effect to take place
