### ISSUE TITLE
Menu Collection - can see only the back of the cards

### ISSUE THREAD

**Issue by Yzia** [mandelmonkey/bookoforbs#2]
Chrome Version 62.0.3202.94 (Build officiel) (64 bits)

Hi,

If you switch between the different menus, and move back to my Orbs, only the back of your card is shown : 

![image](https://user-images.githubusercontent.com/34238756/33671407-ced23496-daa7-11e7-8aed-4ebb0a8f4f55.png)

To get it back, you have to switch to another project, for example Force of Will and go back. The this page is loaded again.

**Comment by Yzia** [comment]
This is the same if you go to "All orbs" + if you do some searches. 

For example on SoG I search in all orbs for "MA", the result shows 2 cards but only the back of its, not the image.

![image](https://user-images.githubusercontent.com/34238756/33674015-ac321346-daae-11e7-9b32-443797496d82.png)

**Comment by mandelmonkey** [comment]
should be fixed now, please re open if not
