### ISSUE TITLE
Menu Market - Asset information

### ISSUE THREAD

**Issue by Yzia** [mandelmonkey/bookoforbs#3]
Chrome Version 62.0.3202.94 (Build officiel) (64 bits)

Hi,

Assets are really large, and the information below all cards are not reported (buyers/sellers). But it's perhaps intended as it's not connected (?)

![image](https://user-images.githubusercontent.com/34238756/33671926-310827a0-daa9-11e7-93ed-b3c537bcdfb1.png)

When you click on an asset to veiw the information, the availability number appears on the left

![image](https://user-images.githubusercontent.com/34238756/33671768-d4ad11fa-daa8-11e7-83e2-1e9851a76d15.png)

**Comment by mandelmonkey** [comment]
fixed this up a bit, please reopen if you have more feedback
