### ISSUE TITLE
Menu - See all App connected

### ISSUE THREAD

**Issue by Yzia** [mandelmonkey/bookoforbs#4]
Chrome Version 62.0.3202.94 (Build officiel) (64 bits)

Hi,

If you click on the arrow of the button to see all the app connected into BoO, it won't appear. You have to click on the text only, not on the arrow. Which is not really user-friendly.

![image](https://user-images.githubusercontent.com/34238756/33672074-98494336-daa9-11e7-965c-69dd06d7a797.png)

**Comment by mandelmonkey** [comment]
should be fixed, reopen if not
