### ISSUE TITLE
History Menu : Image preview linked to transaction sometimes disappears and appears again

### ISSUE THREAD

**Issue by Yzia** [mandelmonkey/bookoforbs#6]
Chrome Version 62.0.3202.94 (Build officiel) (64 bits)

Hi,

The history is sometimes wierd. Sometimes the image linked to your transation appears sometimes not after scrolling into the menu or switch to another one and move back.

![image](https://user-images.githubusercontent.com/34238756/33672693-220df07a-daab-11e7-8eb4-398742846672.png)

**Comment by mandelmonkey** [comment]
should be fixed now, please reopen if not
