### ISSUE TITLE
Card preview

### ISSUE THREAD

**Issue by Yzia** [mandelmonkey/bookoforbs#8]
The title of the card is not really visible (STAGWARRIOR)
There is a black layer around the whole card.
The resolution of the card is not really a high one, perhaps a max-width should be defined.

![image](https://user-images.githubusercontent.com/34238756/34516981-6c49ba5a-f079-11e7-9eff-a91ecaa2706e.png)

**Comment by mandelmonkey** [comment]
Unfortunately I am just displaying the card imgs in the api, shaban needs to supply a higher res version, also the black borders is part of the image.

re the title, you mean its too small? what machine were you using to display? was it a very hi res screen?

**Comment by Yzia** [comment]
I was talking about this name (too small, the resolution of the screen won't change anything, the size is small comparing to the card display) :

![image](https://user-images.githubusercontent.com/34238756/34994883-2d504baa-fad5-11e7-9a04-6d7d7616ab6a.png)

Just in case my screen resolution is : 1366x768

**Comment by mandelmonkey** [comment]
ah ok I increased the font, but it never looked as small on my computer so let me know if its still small
